name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'SpinShareClient/**'

jobs:
  build:
    name: build-${{ matrix.os }}
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Create Folder Structure for Archive
        run: |
          mkdir -p artifacts/${{ matrix.os }}
          cp -r SpinShareClient/bin/Release/net7.0/* artifacts/${{ matrix.os }}/
          ls -lp artifacts/${{ matrix.os }}
      - name: Archive build artifacts
        uses: vimtor/action-zip@v1
        with:
          files: artifacts/${{ matrix.os }}
          dest: artifacts/${{ matrix.os }}.zip
      - name: List Files
        run: |
          ls -lp artifacts
      - name: Save Release Artifact
        uses: actions/upload-artifact@v2
        with:
          path: artifacts/${{ matrix.os }}.zip
          name: ${{ matrix.os }}.zip
          retention-days: 1
  release:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Release Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: List Files
        run: |
          ls -lp artifacts/macos-latest.zip/macos-latest.zip
          ls -lp artifacts/ubuntu-latest.zip/ubuntu-latest.zip
          ls -lp artifacts/windows-latest.zip/windows-latest.zip
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/macos-latest.zip/macos-latest.zip
            artifacts/ubuntu-latest.zip/ubuntu-latest.zip
            artifacts/windows-latest.zip/windows-latest.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          name: Release ${{ github.event.repository.updated_at }}
          draft: true
          prerelease: true
    